import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import Image from "next/image";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex   items-center   bg-zinc-50 font-sans dark:bg-black">
   <Button>click heare</Button>
    </div>
  );
}
